import type { Client, Message, RevenueData, WorkoutLog, WorkoutProgram } from './types';

const avatarColors = [
  '#00e5c8', '#6366f1', '#f59e0b', '#ef4444', '#22c55e',
  '#ec4899', '#8b5cf6', '#06b6d4', '#f97316', '#14b8a6',
];

export function getInitials(name: string): string {
  return name.split(' ').map(n => n[0]).join('').toUpperCase();
}

export function getAvatarColor(id: string): string {
  const idx = id.split('').reduce((acc, ch) => acc + ch.charCodeAt(0), 0);
  return avatarColors[idx % avatarColors.length];
}

export const clients: Client[] = [
  {
    id: 'c1',
    name: 'Marcus Chen',
    avatar: '',
    email: 'marcus@example.com',
    plan: 'Elite',
    status: 'active',
    startDate: '2025-08-15',
    nextCheckIn: '2026-02-22',
    monthlyRate: 299,
    progress: 82,
    metrics: {
      weight: [95, 93, 91, 89.5, 88, 87, 86],
      bodyFat: [22, 21, 20, 19, 18.5, 17.8, 17],
      benchPress: [80, 85, 87.5, 90, 92.5, 95, 100],
      squat: [100, 110, 115, 120, 125, 130, 140],
      deadlift: [120, 130, 135, 140, 145, 150, 160],
    },
    goals: ['Lose 10kg', 'Bench 120kg', 'Run 5K under 25min'],
    notes: 'Responding well to progressive overload. Increase volume next phase.',
    lastActive: '2 hours ago',
    streak: 14,
  },
  {
    id: 'c2',
    name: 'Sarah Williams',
    avatar: '',
    email: 'sarah@example.com',
    plan: 'Premium',
    status: 'active',
    startDate: '2025-10-01',
    nextCheckIn: '2026-02-23',
    monthlyRate: 199,
    progress: 68,
    metrics: {
      weight: [70, 69, 68.5, 68, 67.5, 67, 66.5],
      bodyFat: [28, 27, 26.5, 26, 25, 24.5, 24],
      benchPress: [30, 32.5, 35, 37.5, 40, 40, 42.5],
      squat: [50, 55, 60, 65, 67.5, 70, 75],
      deadlift: [60, 65, 70, 75, 80, 82.5, 85],
    },
    goals: ['Tone up', 'First pull-up', 'Improve mobility'],
    notes: 'Knee issue — avoid deep squats. Focus on hip hinge patterns.',
    lastActive: '5 hours ago',
    streak: 8,
  },
  {
    id: 'c3',
    name: 'Jake Morrison',
    avatar: '',
    email: 'jake@example.com',
    plan: 'Elite',
    status: 'active',
    startDate: '2025-06-10',
    nextCheckIn: '2026-02-21',
    monthlyRate: 299,
    progress: 91,
    metrics: {
      weight: [82, 83, 83.5, 84, 84, 84.5, 85],
      bodyFat: [15, 14.5, 14, 13.5, 13, 12.5, 12],
      benchPress: [100, 105, 107.5, 110, 115, 117.5, 120],
      squat: [140, 145, 150, 155, 157.5, 160, 165],
      deadlift: [170, 175, 180, 185, 190, 195, 200],
    },
    goals: ['Compete in powerlifting', 'Total 500kg', 'Sub-10% BF'],
    notes: 'Competition prep phase. Peak week starts March 1.',
    lastActive: '30 min ago',
    streak: 32,
  },
  {
    id: 'c4',
    name: 'Emma Rodriguez',
    avatar: '',
    email: 'emma@example.com',
    plan: 'Basic',
    status: 'pending',
    startDate: '2026-02-10',
    nextCheckIn: '2026-02-24',
    monthlyRate: 99,
    progress: 15,
    metrics: {
      weight: [75, 74.5],
      bodyFat: [30, 29.5],
      benchPress: [20, 22.5],
      squat: [30, 35],
      deadlift: [40, 45],
    },
    goals: ['Get started', 'Build consistency', 'Feel stronger'],
    notes: 'Complete beginner. Focus on form and habit-building.',
    lastActive: '1 day ago',
    streak: 3,
  },
  {
    id: 'c5',
    name: 'David Park',
    avatar: '',
    email: 'david@example.com',
    plan: 'Premium',
    status: 'active',
    startDate: '2025-09-20',
    nextCheckIn: '2026-02-25',
    monthlyRate: 199,
    progress: 73,
    metrics: {
      weight: [88, 87, 86, 85, 84.5, 84, 83],
      bodyFat: [20, 19.5, 19, 18.5, 18, 17.5, 17],
      benchPress: [70, 75, 77.5, 80, 82.5, 85, 87.5],
      squat: [90, 95, 100, 105, 110, 112.5, 115],
      deadlift: [110, 115, 120, 125, 130, 135, 140],
    },
    goals: ['Visible abs', 'Run a half-marathon', 'Improve sleep'],
    notes: 'Shift worker — adjust training times. Nutrition tracking is key.',
    lastActive: '4 hours ago',
    streak: 11,
  },
  {
    id: 'c6',
    name: 'Lisa Thompson',
    avatar: '',
    email: 'lisa@example.com',
    plan: 'Elite',
    status: 'paused',
    startDate: '2025-07-01',
    nextCheckIn: '—',
    monthlyRate: 299,
    progress: 55,
    metrics: {
      weight: [63, 62.5, 62, 62, 63, 63.5],
      bodyFat: [24, 23.5, 23, 23, 23.5, 24],
      benchPress: [35, 37.5, 40, 42.5, 40, 40],
      squat: [60, 65, 70, 72.5, 70, 68],
      deadlift: [70, 75, 80, 85, 82, 80],
    },
    goals: ['Return from injury', 'Rebuild strength', 'Pain-free training'],
    notes: 'Paused — recovering from shoulder injury. Check in March 1.',
    lastActive: '2 weeks ago',
    streak: 0,
  },
  {
    id: 'c7',
    name: 'Tom Bradley',
    avatar: '',
    email: 'tom@example.com',
    plan: 'Premium',
    status: 'active',
    startDate: '2025-11-15',
    nextCheckIn: '2026-02-22',
    monthlyRate: 199,
    progress: 60,
    metrics: {
      weight: [105, 103, 101, 99, 97, 96],
      bodyFat: [28, 27, 26, 25, 24, 23.5],
      benchPress: [90, 92.5, 95, 97.5, 100, 100],
      squat: [120, 122.5, 125, 130, 132.5, 135],
      deadlift: [140, 145, 147.5, 150, 155, 157.5],
    },
    goals: ['Drop to 90kg', 'Maintain strength', 'Better cardio'],
    notes: 'Great adherence. Cardio improving steadily. Keep pushing.',
    lastActive: '1 hour ago',
    streak: 19,
  },
  {
    id: 'c8',
    name: 'Aisha Patel',
    avatar: '',
    email: 'aisha@example.com',
    plan: 'Basic',
    status: 'active',
    startDate: '2025-12-01',
    nextCheckIn: '2026-02-26',
    monthlyRate: 99,
    progress: 40,
    metrics: {
      weight: [58, 58, 57.5, 57],
      bodyFat: [26, 25.5, 25, 24.5],
      benchPress: [20, 22.5, 25, 27.5],
      squat: [35, 40, 45, 50],
      deadlift: [45, 50, 55, 60],
    },
    goals: ['Build muscle', 'Improve posture', 'Gain confidence'],
    notes: 'Progressing well for 3 months in. Increase protein target.',
    lastActive: '6 hours ago',
    streak: 6,
  },
  // ── Potential clients (email leads) ──
  {
    id: 'c9',
    name: 'Ryan Kowalski',
    avatar: '',
    email: 'ryan.kowalski@gmail.com',
    plan: 'Basic',
    status: 'pending',
    startDate: '',
    nextCheckIn: '',
    monthlyRate: 0,
    progress: 0,
    metrics: { weight: [], bodyFat: [], benchPress: [], squat: [], deadlift: [] },
    goals: ['Lose 15kg', 'Run a 5K'],
    notes: 'Inbound lead from Instagram. Interested in weight loss coaching.',
    lastActive: '1 day ago',
    streak: 0,
  },
  {
    id: 'c10',
    name: 'Natalie Souza',
    avatar: '',
    email: 'natalie.souza@outlook.com',
    plan: 'Premium',
    status: 'pending',
    startDate: '',
    nextCheckIn: '',
    monthlyRate: 0,
    progress: 0,
    metrics: { weight: [], bodyFat: [], benchPress: [], squat: [], deadlift: [] },
    goals: ['Body recomp', 'Compete in bikini'],
    notes: 'Referral from Marcus Chen. Experienced lifter looking for comp prep.',
    lastActive: '3 hours ago',
    streak: 0,
  },
];

export const messages: Message[] = [
  // Marcus Chen — bench PR conversation (via Telegram)
  {
    id: 'm1a', clientId: 'c1', clientName: 'Marcus Chen', clientAvatar: '',
    text: 'How did the bench session feel today? You were due for a heavy single.',
    timestamp: '2026-02-20T13:00:00', isRead: true, isFromCoach: true, channel: 'telegram',
  },
  {
    id: 'm1b', clientId: 'c1', clientName: 'Marcus Chen', clientAvatar: '',
    text: 'Felt amazing honestly. Warm-ups were flying.',
    timestamp: '2026-02-20T13:45:00', isRead: true, isFromCoach: false, channel: 'telegram',
  },
  {
    id: 'm1', clientId: 'c1', clientName: 'Marcus Chen', clientAvatar: '',
    text: 'Hit a new PR on bench today! 102.5kg for 2 reps. Feeling strong.',
    timestamp: '2026-02-20T14:30:00', isRead: false, isFromCoach: false, channel: 'telegram',
  },
  // Jake Morrison — deload question (via WhatsApp)
  {
    id: 'm2a', clientId: 'c3', clientName: 'Jake Morrison', clientAvatar: '',
    text: 'Squats felt heavy yesterday, RPE was way higher than usual.',
    timestamp: '2026-02-20T12:00:00', isRead: true, isFromCoach: false, channel: 'whatsapp',
  },
  {
    id: 'm2', clientId: 'c3', clientName: 'Jake Morrison', clientAvatar: '',
    text: 'Coach, should I deload this week before peak? Feeling a bit beat up.',
    timestamp: '2026-02-20T13:15:00', isRead: false, isFromCoach: false, channel: 'whatsapp',
  },
  // Emma Rodriguez — first workout (via WhatsApp)
  {
    id: 'm3', clientId: 'c4', clientName: 'Emma Rodriguez', clientAvatar: '',
    text: "Had my first workout today — it was tough but I loved it! Thanks for the program.",
    timestamp: '2026-02-20T11:45:00', isRead: false, isFromCoach: false, channel: 'whatsapp',
  },
  // Sarah Williams — knee rehab conversation
  {
    id: 'm4a', clientId: 'c2', clientName: 'Sarah Williams', clientAvatar: '',
    text: "How's the knee feeling with the modified squats?",
    timestamp: '2026-02-20T09:30:00', isRead: true, isFromCoach: true,
  },
  {
    id: 'm4', clientId: 'c2', clientName: 'Sarah Williams', clientAvatar: '',
    text: "My knee felt great during today's session. The modified program is working!",
    timestamp: '2026-02-20T10:00:00', isRead: true, isFromCoach: false,
  },
  {
    id: 'm5', clientId: 'c2', clientName: 'Sarah Williams', clientAvatar: '',
    text: "Great to hear! Let's test some deeper range next week if it stays comfortable.",
    timestamp: '2026-02-20T10:15:00', isRead: true, isFromCoach: true,
  },
  {
    id: 'm5a', clientId: 'c2', clientName: 'Sarah Williams', clientAvatar: '',
    text: "Sounds good! I'm excited to push a bit further.",
    timestamp: '2026-02-20T10:20:00', isRead: true, isFromCoach: false,
  },
  // David Park — missed session (via Email)
  {
    id: 'm6', clientId: 'c5', clientName: 'David Park', clientAvatar: '',
    text: 'Missed yesterday — double shift at work. Will make it up tomorrow morning.',
    timestamp: '2026-02-19T22:30:00', isRead: true, isFromCoach: false, channel: 'email',
  },
  {
    id: 'm6a', clientId: 'c5', clientName: 'David Park', clientAvatar: '',
    text: "No worries, life happens. Just don't skip two in a row — keep the momentum going.",
    timestamp: '2026-02-19T22:45:00', isRead: true, isFromCoach: true, channel: 'email',
  },
  // Tom Bradley — weight milestone (via Telegram)
  {
    id: 'm7', clientId: 'c7', clientName: 'Tom Bradley', clientAvatar: '',
    text: 'Weighed in at 95.8kg this morning! First time under 96 in years.',
    timestamp: '2026-02-19T08:00:00', isRead: true, isFromCoach: false, channel: 'telegram',
  },
  {
    id: 'm8', clientId: 'c7', clientName: 'Tom Bradley', clientAvatar: '',
    text: "Incredible progress Tom! That's 9kg down. Let's celebrate that win.",
    timestamp: '2026-02-19T09:30:00', isRead: true, isFromCoach: true, channel: 'telegram',
  },
  {
    id: 'm8a', clientId: 'c7', clientName: 'Tom Bradley', clientAvatar: '',
    text: "Thanks coach! Couldn't have done it without the accountability. What's next?",
    timestamp: '2026-02-19T09:45:00', isRead: true, isFromCoach: false, channel: 'telegram',
  },
  {
    id: 'm8b', clientId: 'c7', clientName: 'Tom Bradley', clientAvatar: '',
    text: "Next target: 93kg by end of March. We'll bump cardio slightly and keep protein high.",
    timestamp: '2026-02-19T10:00:00', isRead: true, isFromCoach: true, channel: 'telegram',
  },
  // Aisha Patel — program request
  {
    id: 'm9', clientId: 'c8', clientName: 'Aisha Patel', clientAvatar: '',
    text: 'Can we add a glute day? I feel like I need more lower body focus.',
    timestamp: '2026-02-19T16:00:00', isRead: true, isFromCoach: false,
  },
  {
    id: 'm9a', clientId: 'c8', clientName: 'Aisha Patel', clientAvatar: '',
    text: "Absolutely. I'll swap Friday's session to a glute/hamstring focus. Check your program tomorrow.",
    timestamp: '2026-02-19T16:30:00', isRead: true, isFromCoach: true,
  },
  // Ryan Kowalski — potential client inquiry (via Email)
  {
    id: 'm10', clientId: 'c9', clientName: 'Ryan Kowalski', clientAvatar: '',
    text: "Hi Coach Kamil, I found you on Instagram and I'm really interested in your coaching. I'm 32, about 105kg and want to lose weight properly this time. I've tried diets before but nothing sticks. Do you offer online coaching? What are your rates?",
    timestamp: '2026-02-20T08:15:00', isRead: false, isFromCoach: false, channel: 'email',
  },
  {
    id: 'm10a', clientId: 'c9', clientName: 'Ryan Kowalski', clientAvatar: '',
    text: "Hey Ryan! Thanks for reaching out. I totally understand the frustration with yo-yo dieting. My approach is sustainable — we build habits, not just meal plans. I offer 3 tiers starting at $99/mo. Want to book a free 15-min discovery call this week?",
    timestamp: '2026-02-20T10:00:00', isRead: true, isFromCoach: true, channel: 'email',
  },
  {
    id: 'm10b', clientId: 'c9', clientName: 'Ryan Kowalski', clientAvatar: '',
    text: "That sounds great! I'm free Thursday afternoon or Friday morning. Also, do you provide meal plans or just training?",
    timestamp: '2026-02-20T14:20:00', isRead: false, isFromCoach: false, channel: 'email',
  },
  // Natalie Souza — referral from Marcus (via Email)
  {
    id: 'm11', clientId: 'c10', clientName: 'Natalie Souza', clientAvatar: '',
    text: "Hi! Marcus Chen referred me to you. I've been lifting for 4 years and I'm looking to do my first bikini competition later this year. I need a coach who understands periodization and peak week. Do you have experience with contest prep?",
    timestamp: '2026-02-21T07:30:00', isRead: false, isFromCoach: false, channel: 'email',
  },
  {
    id: 'm11a', clientId: 'c10', clientName: 'Natalie Souza', clientAvatar: '',
    text: "Marcus is a great client — glad he sent you my way! I've coached 3 competitors through their preps. For comp prep I'd recommend the Elite tier ($299/mo) which includes daily check-ins, posing feedback, and peak week protocol. When's your target show date?",
    timestamp: '2026-02-21T09:00:00', isRead: true, isFromCoach: true, channel: 'email',
  },
  {
    id: 'm11b', clientId: 'c10', clientName: 'Natalie Souza', clientAvatar: '',
    text: "I'm looking at a show in late September — so about 7 months out. That gives us plenty of time for a proper off-season into prep. Can we set up a video call to discuss the plan?",
    timestamp: '2026-02-21T11:45:00', isRead: false, isFromCoach: false, channel: 'email',
  },
];

export const revenueData: RevenueData[] = [
  { month: 'Sep', revenue: 1495, clients: 5 },
  { month: 'Oct', revenue: 1694, clients: 6 },
  { month: 'Nov', revenue: 1893, clients: 7 },
  { month: 'Dec', revenue: 1992, clients: 8 },
  { month: 'Jan', revenue: 1693, clients: 7 },
  { month: 'Feb', revenue: 1692, clients: 8 },
];

export const workoutLogs: WorkoutLog[] = [
  // ── Marcus Chen (c1) — 4-5x/week ──
  { id: 'w1-01', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 75, date: '2026-02-20', completed: true },
  { id: 'w1-02', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 70, date: '2026-02-18', completed: true },
  { id: 'w1-03', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 65, date: '2026-02-17', completed: true },
  { id: 'w1-04', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body B', duration: 70, date: '2026-02-15', completed: true },
  { id: 'w1-05', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 75, date: '2026-02-13', completed: true },
  { id: 'w1-06', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 70, date: '2026-02-11', completed: true },
  { id: 'w1-07', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 65, date: '2026-02-10', completed: true },
  { id: 'w1-08', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body B', duration: 72, date: '2026-02-08', completed: false },
  { id: 'w1-09', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 75, date: '2026-02-06', completed: true },
  { id: 'w1-10', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 68, date: '2026-02-04', completed: true },
  { id: 'w1-11', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 70, date: '2026-02-03', completed: true },
  { id: 'w1-12', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body B', duration: 65, date: '2026-02-01', completed: true },
  { id: 'w1-13', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 75, date: '2026-01-30', completed: true },
  { id: 'w1-14', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 70, date: '2026-01-28', completed: true },
  { id: 'w1-15', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 65, date: '2026-01-27', completed: true },
  { id: 'w1-16', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body B', duration: 70, date: '2026-01-25', completed: true },
  { id: 'w1-17', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 72, date: '2026-01-23', completed: true },
  { id: 'w1-18', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 68, date: '2026-01-21', completed: false },
  { id: 'w1-19', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 70, date: '2026-01-20', completed: true },
  { id: 'w1-20', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body B', duration: 65, date: '2026-01-18', completed: true },
  { id: 'w1-21', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body A', duration: 75, date: '2026-01-16', completed: true },
  { id: 'w1-22', clientId: 'c1', clientName: 'Marcus Chen', type: 'Lower Body A', duration: 70, date: '2026-01-14', completed: true },
  { id: 'w1-23', clientId: 'c1', clientName: 'Marcus Chen', type: 'Upper Body B', duration: 68, date: '2026-01-12', completed: true },

  // ── Sarah Williams (c2) — 3-4x/week ──
  { id: 'w2-01', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 55, date: '2026-02-20', completed: true },
  { id: 'w2-02', clientId: 'c2', clientName: 'Sarah Williams', type: 'Upper Body', duration: 50, date: '2026-02-18', completed: true },
  { id: 'w2-03', clientId: 'c2', clientName: 'Sarah Williams', type: 'Full Body', duration: 55, date: '2026-02-16', completed: true },
  { id: 'w2-04', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 50, date: '2026-02-13', completed: true },
  { id: 'w2-05', clientId: 'c2', clientName: 'Sarah Williams', type: 'Upper Body', duration: 48, date: '2026-02-11', completed: true },
  { id: 'w2-06', clientId: 'c2', clientName: 'Sarah Williams', type: 'Full Body', duration: 55, date: '2026-02-09', completed: false },
  { id: 'w2-07', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 52, date: '2026-02-06', completed: true },
  { id: 'w2-08', clientId: 'c2', clientName: 'Sarah Williams', type: 'Upper Body', duration: 50, date: '2026-02-04', completed: true },
  { id: 'w2-09', clientId: 'c2', clientName: 'Sarah Williams', type: 'Full Body', duration: 55, date: '2026-02-02', completed: true },
  { id: 'w2-10', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 50, date: '2026-01-30', completed: true },
  { id: 'w2-11', clientId: 'c2', clientName: 'Sarah Williams', type: 'Upper Body', duration: 48, date: '2026-01-28', completed: true },
  { id: 'w2-12', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 50, date: '2026-01-25', completed: true },
  { id: 'w2-13', clientId: 'c2', clientName: 'Sarah Williams', type: 'Full Body', duration: 55, date: '2026-01-23', completed: false },
  { id: 'w2-14', clientId: 'c2', clientName: 'Sarah Williams', type: 'Upper Body', duration: 48, date: '2026-01-21', completed: true },
  { id: 'w2-15', clientId: 'c2', clientName: 'Sarah Williams', type: 'Lower Body', duration: 52, date: '2026-01-18', completed: true },

  // ── Jake Morrison (c3) — 5-6x/week (powerlifter) ──
  { id: 'w3-01', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 90, date: '2026-02-20', completed: true },
  { id: 'w3-02', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-02-19', completed: true },
  { id: 'w3-03', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 80, date: '2026-02-18', completed: true },
  { id: 'w3-04', clientId: 'c3', clientName: 'Jake Morrison', type: 'Accessories', duration: 60, date: '2026-02-17', completed: true },
  { id: 'w3-05', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 90, date: '2026-02-16', completed: true },
  { id: 'w3-06', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-02-14', completed: true },
  { id: 'w3-07', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 82, date: '2026-02-13', completed: true },
  { id: 'w3-08', clientId: 'c3', clientName: 'Jake Morrison', type: 'Accessories', duration: 55, date: '2026-02-12', completed: true },
  { id: 'w3-09', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 88, date: '2026-02-11', completed: true },
  { id: 'w3-10', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-02-09', completed: true },
  { id: 'w3-11', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 80, date: '2026-02-07', completed: true },
  { id: 'w3-12', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 92, date: '2026-02-06', completed: true },
  { id: 'w3-13', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-02-04', completed: true },
  { id: 'w3-14', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 78, date: '2026-02-03', completed: false },
  { id: 'w3-15', clientId: 'c3', clientName: 'Jake Morrison', type: 'Accessories', duration: 60, date: '2026-02-02', completed: true },
  { id: 'w3-16', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 90, date: '2026-01-31', completed: true },
  { id: 'w3-17', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-01-30', completed: true },
  { id: 'w3-18', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 80, date: '2026-01-28', completed: true },
  { id: 'w3-19', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 88, date: '2026-01-27', completed: true },
  { id: 'w3-20', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-01-25', completed: true },
  { id: 'w3-21', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 82, date: '2026-01-23', completed: true },
  { id: 'w3-22', clientId: 'c3', clientName: 'Jake Morrison', type: 'Accessories', duration: 58, date: '2026-01-22', completed: true },
  { id: 'w3-23', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 90, date: '2026-01-20', completed: true },
  { id: 'w3-24', clientId: 'c3', clientName: 'Jake Morrison', type: 'Bench Day', duration: 85, date: '2026-01-18', completed: true },
  { id: 'w3-25', clientId: 'c3', clientName: 'Jake Morrison', type: 'Deadlift Day', duration: 80, date: '2026-01-16', completed: true },
  { id: 'w3-26', clientId: 'c3', clientName: 'Jake Morrison', type: 'Squat Day', duration: 90, date: '2026-01-14', completed: true },

  // ── Emma Rodriguez (c4) — 3x/week (beginner) ──
  { id: 'w4-01', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body A', duration: 45, date: '2026-02-20', completed: true },
  { id: 'w4-02', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body B', duration: 40, date: '2026-02-18', completed: true },
  { id: 'w4-03', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body A', duration: 45, date: '2026-02-15', completed: true },
  { id: 'w4-04', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body B', duration: 42, date: '2026-02-13', completed: false },
  { id: 'w4-05', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body A', duration: 45, date: '2026-02-11', completed: true },
  { id: 'w4-06', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body B', duration: 40, date: '2026-02-08', completed: true },
  { id: 'w4-07', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body A', duration: 43, date: '2026-02-06', completed: true },
  { id: 'w4-08', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body B', duration: 40, date: '2026-02-04', completed: true },
  { id: 'w4-09', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body A', duration: 45, date: '2026-02-01', completed: false },
  { id: 'w4-10', clientId: 'c4', clientName: 'Emma Rodriguez', type: 'Full Body B', duration: 38, date: '2026-01-29', completed: true },

  // ── David Park (c5) — 3-4x/week ──
  { id: 'w5-01', clientId: 'c5', clientName: 'David Park', type: 'Push Day', duration: 65, date: '2026-02-20', completed: false },
  { id: 'w5-02', clientId: 'c5', clientName: 'David Park', type: 'Pull Day', duration: 60, date: '2026-02-18', completed: true },
  { id: 'w5-03', clientId: 'c5', clientName: 'David Park', type: 'Leg Day', duration: 65, date: '2026-02-16', completed: true },
  { id: 'w5-04', clientId: 'c5', clientName: 'David Park', type: 'Push Day', duration: 60, date: '2026-02-13', completed: true },
  { id: 'w5-05', clientId: 'c5', clientName: 'David Park', type: 'Pull Day', duration: 58, date: '2026-02-11', completed: true },
  { id: 'w5-06', clientId: 'c5', clientName: 'David Park', type: 'Leg Day', duration: 65, date: '2026-02-09', completed: false },
  { id: 'w5-07', clientId: 'c5', clientName: 'David Park', type: 'Push Day', duration: 62, date: '2026-02-06', completed: true },
  { id: 'w5-08', clientId: 'c5', clientName: 'David Park', type: 'Pull Day', duration: 60, date: '2026-02-04', completed: true },
  { id: 'w5-09', clientId: 'c5', clientName: 'David Park', type: 'Leg Day', duration: 65, date: '2026-02-02', completed: true },
  { id: 'w5-10', clientId: 'c5', clientName: 'David Park', type: 'Push Day', duration: 60, date: '2026-01-30', completed: true },
  { id: 'w5-11', clientId: 'c5', clientName: 'David Park', type: 'Pull Day', duration: 58, date: '2026-01-28', completed: true },
  { id: 'w5-12', clientId: 'c5', clientName: 'David Park', type: 'Leg Day', duration: 65, date: '2026-01-25', completed: true },
  { id: 'w5-13', clientId: 'c5', clientName: 'David Park', type: 'Push Day', duration: 60, date: '2026-01-23', completed: true },

  // ── Lisa Thompson (c6) — paused, few early entries ──
  { id: 'w6-01', clientId: 'c6', clientName: 'Lisa Thompson', type: 'Upper Body', duration: 50, date: '2026-01-20', completed: true },
  { id: 'w6-02', clientId: 'c6', clientName: 'Lisa Thompson', type: 'Lower Body', duration: 48, date: '2026-01-18', completed: true },
  { id: 'w6-03', clientId: 'c6', clientName: 'Lisa Thompson', type: 'Upper Body', duration: 50, date: '2026-01-15', completed: false },
  { id: 'w6-04', clientId: 'c6', clientName: 'Lisa Thompson', type: 'Lower Body', duration: 45, date: '2026-01-13', completed: true },

  // ── Tom Bradley (c7) — 4x/week ──
  { id: 'w7-01', clientId: 'c7', clientName: 'Tom Bradley', type: 'Full Body', duration: 60, date: '2026-02-20', completed: true },
  { id: 'w7-02', clientId: 'c7', clientName: 'Tom Bradley', type: 'Upper Body', duration: 55, date: '2026-02-18', completed: true },
  { id: 'w7-03', clientId: 'c7', clientName: 'Tom Bradley', type: 'Lower Body', duration: 60, date: '2026-02-16', completed: true },
  { id: 'w7-04', clientId: 'c7', clientName: 'Tom Bradley', type: 'Cardio', duration: 40, date: '2026-02-15', completed: true },
  { id: 'w7-05', clientId: 'c7', clientName: 'Tom Bradley', type: 'Full Body', duration: 62, date: '2026-02-13', completed: true },
  { id: 'w7-06', clientId: 'c7', clientName: 'Tom Bradley', type: 'Upper Body', duration: 55, date: '2026-02-11', completed: true },
  { id: 'w7-07', clientId: 'c7', clientName: 'Tom Bradley', type: 'Lower Body', duration: 60, date: '2026-02-09', completed: true },
  { id: 'w7-08', clientId: 'c7', clientName: 'Tom Bradley', type: 'Cardio', duration: 38, date: '2026-02-08', completed: false },
  { id: 'w7-09', clientId: 'c7', clientName: 'Tom Bradley', type: 'Full Body', duration: 60, date: '2026-02-06', completed: true },
  { id: 'w7-10', clientId: 'c7', clientName: 'Tom Bradley', type: 'Upper Body', duration: 55, date: '2026-02-04', completed: true },
  { id: 'w7-11', clientId: 'c7', clientName: 'Tom Bradley', type: 'Lower Body', duration: 58, date: '2026-02-02', completed: true },
  { id: 'w7-12', clientId: 'c7', clientName: 'Tom Bradley', type: 'Cardio', duration: 40, date: '2026-02-01', completed: true },
  { id: 'w7-13', clientId: 'c7', clientName: 'Tom Bradley', type: 'Full Body', duration: 60, date: '2026-01-30', completed: true },
  { id: 'w7-14', clientId: 'c7', clientName: 'Tom Bradley', type: 'Upper Body', duration: 55, date: '2026-01-28', completed: true },
  { id: 'w7-15', clientId: 'c7', clientName: 'Tom Bradley', type: 'Lower Body', duration: 60, date: '2026-01-26', completed: true },
  { id: 'w7-16', clientId: 'c7', clientName: 'Tom Bradley', type: 'Cardio', duration: 40, date: '2026-01-25', completed: true },
  { id: 'w7-17', clientId: 'c7', clientName: 'Tom Bradley', type: 'Full Body', duration: 62, date: '2026-01-23', completed: true },

  // ── Aisha Patel (c8) — 3x/week ──
  { id: 'w8-01', clientId: 'c8', clientName: 'Aisha Patel', type: 'Upper Body', duration: 50, date: '2026-02-20', completed: false },
  { id: 'w8-02', clientId: 'c8', clientName: 'Aisha Patel', type: 'Lower Body', duration: 48, date: '2026-02-18', completed: true },
  { id: 'w8-03', clientId: 'c8', clientName: 'Aisha Patel', type: 'Full Body', duration: 50, date: '2026-02-15', completed: true },
  { id: 'w8-04', clientId: 'c8', clientName: 'Aisha Patel', type: 'Upper Body', duration: 48, date: '2026-02-13', completed: true },
  { id: 'w8-05', clientId: 'c8', clientName: 'Aisha Patel', type: 'Lower Body', duration: 50, date: '2026-02-11', completed: true },
  { id: 'w8-06', clientId: 'c8', clientName: 'Aisha Patel', type: 'Full Body', duration: 45, date: '2026-02-08', completed: true },
  { id: 'w8-07', clientId: 'c8', clientName: 'Aisha Patel', type: 'Upper Body', duration: 50, date: '2026-02-06', completed: false },
  { id: 'w8-08', clientId: 'c8', clientName: 'Aisha Patel', type: 'Lower Body', duration: 48, date: '2026-02-04', completed: true },
  { id: 'w8-09', clientId: 'c8', clientName: 'Aisha Patel', type: 'Full Body', duration: 50, date: '2026-02-01', completed: true },
  { id: 'w8-10', clientId: 'c8', clientName: 'Aisha Patel', type: 'Upper Body', duration: 45, date: '2026-01-29', completed: true },
  { id: 'w8-11', clientId: 'c8', clientName: 'Aisha Patel', type: 'Lower Body', duration: 48, date: '2026-01-27', completed: true },
];

export const scheduleToday = [
  { time: '07:00', client: 'Jake Morrison', type: 'Squat Day', status: 'completed' as const },
  { time: '09:00', client: 'Marcus Chen', type: 'Upper Body', status: 'completed' as const },
  { time: '11:00', client: 'Sarah Williams', type: 'Lower Body', status: 'completed' as const },
  { time: '14:00', client: 'Tom Bradley', type: 'Full Body', status: 'current' as const },
  { time: '16:00', client: 'David Park', type: 'Push Day', status: 'upcoming' as const },
  { time: '18:00', client: 'Aisha Patel', type: 'Upper Body', status: 'upcoming' as const },
];

export const exerciseLibrary: string[] = [
  'Barbell Back Squat', 'Front Squat', 'Goblet Squat', 'Bulgarian Split Squat',
  'Leg Press', 'Romanian Deadlift', 'Conventional Deadlift', 'Sumo Deadlift',
  'Hip Thrust', 'Leg Extension', 'Leg Curl', 'Calf Raise',
  'Barbell Bench Press', 'Incline Bench Press', 'Dumbbell Bench Press',
  'Overhead Press', 'Dumbbell Shoulder Press', 'Lateral Raise',
  'Barbell Row', 'Dumbbell Row', 'Lat Pulldown', 'Pull-Up', 'Chin-Up',
  'Cable Row', 'Face Pull', 'Rear Delt Fly',
  'Barbell Curl', 'Hammer Curl', 'Tricep Pushdown', 'Skull Crusher',
  'Plank', 'Ab Rollout', 'Cable Crunch', 'Hanging Leg Raise',
  'Lunges', 'Step-Up', 'Glute Bridge', 'Good Morning',
];

export const workoutPrograms: WorkoutProgram[] = [
  {
    id: 'wp1',
    name: 'Hypertrophy Block A',
    status: 'active',
    durationWeeks: 6,
    clientIds: ['c1'],
    isTemplate: false,
    createdAt: '2026-01-15',
    updatedAt: '2026-02-18',
    days: [
      {
        id: 'wd1a',
        name: 'Upper Body A',
        exercises: [
          { id: 'e1', name: 'Barbell Bench Press', sets: 4, reps: '6-8', weight: '90kg', rpe: 8, tempo: '3-1-2-0', restSeconds: 180, notes: '' },
          { id: 'e2', name: 'Barbell Row', sets: 4, reps: '8-10', weight: '75kg', rpe: 7, tempo: '', restSeconds: 120, notes: '' },
          { id: 'e3', name: 'Overhead Press', sets: 3, reps: '8-12', weight: '50kg', rpe: 7, tempo: '', restSeconds: 120, notes: '' },
          { id: 'e4', name: 'Lateral Raise', sets: 3, reps: '12-15', weight: '12kg', rpe: null, tempo: '', restSeconds: 60, notes: 'Controlled eccentric' },
        ],
      },
      {
        id: 'wd1b',
        name: 'Lower Body A',
        exercises: [
          { id: 'e5', name: 'Barbell Back Squat', sets: 4, reps: '5-6', weight: '120kg', rpe: 8, tempo: '3-1-2-0', restSeconds: 240, notes: 'Belt on working sets' },
          { id: 'e6', name: 'Romanian Deadlift', sets: 3, reps: '8-10', weight: '100kg', rpe: 7, tempo: '3-0-1-0', restSeconds: 120, notes: '' },
          { id: 'e7', name: 'Leg Press', sets: 3, reps: '10-12', weight: '180kg', rpe: null, tempo: '', restSeconds: 120, notes: '' },
          { id: 'e8', name: 'Calf Raise', sets: 4, reps: '12-15', weight: '60kg', rpe: null, tempo: '2-1-1-0', restSeconds: 60, notes: '' },
        ],
      },
    ],
  },
  {
    id: 'wp2',
    name: 'Powerlifting Peak',
    status: 'active',
    durationWeeks: 4,
    clientIds: ['c3'],
    isTemplate: false,
    createdAt: '2026-02-01',
    updatedAt: '2026-02-20',
    days: [
      {
        id: 'wd2a',
        name: 'Squat Day',
        exercises: [
          { id: 'e9', name: 'Barbell Back Squat', sets: 5, reps: '3', weight: '155kg', rpe: 9, tempo: '', restSeconds: 300, notes: 'Competition stance' },
          { id: 'e10', name: 'Front Squat', sets: 3, reps: '5', weight: '120kg', rpe: 7, tempo: '', restSeconds: 180, notes: '' },
          { id: 'e11', name: 'Leg Extension', sets: 3, reps: '10-12', weight: '', rpe: null, tempo: '', restSeconds: 90, notes: '' },
        ],
      },
      {
        id: 'wd2b',
        name: 'Bench Day',
        exercises: [
          { id: 'e12', name: 'Barbell Bench Press', sets: 5, reps: '3', weight: '115kg', rpe: 9, tempo: '', restSeconds: 300, notes: 'Competition pause' },
          { id: 'e13', name: 'Incline Bench Press', sets: 3, reps: '6-8', weight: '80kg', rpe: 7, tempo: '', restSeconds: 180, notes: '' },
          { id: 'e14', name: 'Tricep Pushdown', sets: 3, reps: '12-15', weight: '', rpe: null, tempo: '', restSeconds: 60, notes: '' },
        ],
      },
    ],
  },
  {
    id: 'wp3',
    name: 'Beginner Full Body Template',
    status: 'draft',
    durationWeeks: 8,
    clientIds: [],
    isTemplate: true,
    createdAt: '2026-01-10',
    updatedAt: '2026-01-10',
    days: [
      {
        id: 'wd3a',
        name: 'Full Body A',
        exercises: [
          { id: 'e15', name: 'Goblet Squat', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '2-1-2-0', restSeconds: 90, notes: 'Focus on form' },
          { id: 'e16', name: 'Dumbbell Bench Press', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '', restSeconds: 90, notes: '' },
          { id: 'e17', name: 'Lat Pulldown', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '', restSeconds: 90, notes: '' },
          { id: 'e18', name: 'Plank', sets: 3, reps: '30s', weight: '', rpe: null, tempo: '', restSeconds: 60, notes: '' },
        ],
      },
      {
        id: 'wd3b',
        name: 'Full Body B',
        exercises: [
          { id: 'e19', name: 'Romanian Deadlift', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '3-0-1-0', restSeconds: 90, notes: 'Hip hinge cue' },
          { id: 'e20', name: 'Dumbbell Shoulder Press', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '', restSeconds: 90, notes: '' },
          { id: 'e21', name: 'Cable Row', sets: 3, reps: '10-12', weight: '', rpe: 6, tempo: '', restSeconds: 90, notes: '' },
          { id: 'e22', name: 'Glute Bridge', sets: 3, reps: '12-15', weight: '', rpe: null, tempo: '', restSeconds: 60, notes: '' },
        ],
      },
    ],
  },
];
